### ISSUE TITLE
Leader dismount glitch (kig-cai) 

### ISSUE THREAD

**Issue by roccodev** [ProjectKig/KigPaper#1]
[Regression from regular Paper]
In order to ignore `EntityDismountEvent`s triggered by Bukkit's Entity#eject, we check if the player is sneaking (LivingEntity class), which is error prone due to latency etc.

A solution would be to add a flag/enum as the cause of the dismount event, either natural or triggered via Bukkit.

I have a possible fix stashed locally, though I'll need to check all the possible ways the event can be fired.

Effect: leaders can dismount sometimes because they're not sneaking server side

**Comment by andreasdc** [comment]
Cancelling event doesn't cancel bukkit ejecting, but normally you can't eject, why? Before this update of course.
