### ISSUE TITLE
DismountCause is always NATURAL

### ISSUE THREAD

**Issue by andreasdc** [ProjectKig/KigPaper#3]
As in the title

**Comment by andreasdc** [comment]
@RoccoDev @archer-321

**Comment by roccodev** [comment]
It should be `BUKKIT` if you use `Entity#eject` (as opposed to calling `setPassenger(null)` on the vehicle).

**Comment by andreasdc** [comment]
I'm checking it right now, I remember when using entity remove it was natural

**Comment by andreasdc** [comment]
I use player.eject(); and I can't eject

**Comment by roccodev** [comment]
Could you show more of your code? We use `eject` in production and we're able to cancel the natural events (while allowing the call to go through) just fine.

**Comment by andreasdc** [comment]
Code is a little bit more complex, but I use player.eject and cause is natural.

**Comment by andreasdc** [comment]
Additionally player.eject() is returning false
So I should use eject on vehicle not passenger as I see?

**Comment by roccodev** [comment]
Yep, eject should be called on the vehicle. In fact, it returns whether the entity had a passenger, which in this case is false for the passenger.

**Comment by andreasdc** [comment]
> Yep, eject should be called on the vehicle. In fact, it returns whether the entity had a passenger, which in this case is false for the passenger.

Yea, that's weird, but mystery solved. :)

**Comment by andreasdc** [comment]
@RoccoDev does it work with custom entities?

**Comment by roccodev** [comment]
It depends on how they're implemented, but it's not something we support either way.

**Comment by andreasdc** [comment]
> It depends on how they're implemented, but it's not something we support either way.

How can custom entities be implemented to work/don't work?
